### ISSUE TITLE
Milestone 1: Map

### ISSUE THREAD

**Issue by stevenwu2019** [CMU-17-356/cmu-17-356-final-project-s23-flurry#4]
As the organizer for CMU shuttles, I want to see where slip incidents are occurring more frequently around Pittsburgh so my vehicles know where to be more cautious on their regular routes.

**Comment by emmaline01** [comment]
Details: Full map display with filtering by date/time functionality, connected to the Flurry backend so that new incidents that are reported also show up on the map after a refresh
